export const data = [
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"FGD01700",
        Item_Group:"Bakhoor WIP",
        Item_Category:"Bakhoor Mix",
        Item_Name:"BAKHOOR MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
]